# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 819)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.UploadButton.setGeometry(QtCore.QRect(340, 110, 141, 41))
        self.UploadButton.setStyleSheet("font: 75 italic 16pt \"Palatino Linotype\";\n"
"font: 75 italic 14pt \"Palatino Linotype\";")
        self.UploadButton.setObjectName("UploadButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(70, 260, 681, 151))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.filelabel = QtWidgets.QLabel(self.centralwidget)
        self.filelabel.setGeometry(QtCore.QRect(350, 190, 141, 41))
        self.filelabel.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";")
        self.filelabel.setObjectName("filelabel")
        self.SearchLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchLineEdit.setGeometry(QtCore.QRect(60, 440, 181, 31))
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(260, 440, 93, 31))
        self.SearchButton.setStyleSheet("font: 9pt \"Mongolian Baiti\";")
        self.SearchButton.setObjectName("SearchButton")
        self.resultBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.resultBrowser.setGeometry(QtCore.QRect(50, 520, 721, 192))
        self.resultBrowser.setObjectName("resultBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UploadButton.setText(_translate("MainWindow", "Upload File"))
        self.filelabel.setText(_translate("MainWindow", "No file selected"))
        self.SearchLineEdit.setPlaceholderText(_translate("MainWindow", "Enter the value to search.."))
        self.SearchButton.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
